### ISSUE TITLE
GPA function query

### ISSUE THREAD

**Issue by bernard-liew** [geomorphR/geomorph#12]
Hi I am new to the geomorph package, but want to use it for human biomechanics analysis of gait. Can one perform only subsets of translation, scaling, and rotation of the GPA function, rather than all 3? I am asking this as I would like to try combinations of the three functions on my data, to see what makes the most sense.

Kind regards,
Bernard

**Comment by deanadams** [comment]
Bernard,

No, geomorph does not permit one to perform each step of GPA separately. However, with a little R-coding this can be done rather easily for a single iteration (optimal rotation for multiple specimens requires multiple iterations).  The underlying code for gpagen and its sub-funcitons contains this.

Alternatively, the simpler funcitons in Julien Claude’s Morphometrics in R book contains code that can be adapted for each step also.

Dean

Dr. Dean C. Adams
Professor
Department of Ecology, Evolution, and Organismal Biology
       Department of Statistics
Iowa State University
www.public.iastate.edu/~dcadams/<http://www.public.iastate.edu/~dcadams/>
phone: 515-294-3834

**Comment by mlcollyer** [comment]
Bernard,

I believe also that the shapes and Morpho packages have Procrustes superimposition functions that allow one to toggle scaling options and other flexibilities.  One thing to point out though, in geomorph we stick to partial Procrustes superimposition that along with projection into the tangent space produces variables (Procrustes residuals or their principal component scores) that are appropriate for the statistical analyses that our package also promotes.  To allow flexibility in these components of GPA means to violate assumptions about the dispersion of shapes in the space where statistical analyses are performed.  Therefore, I urge caution if you omit some steps in the partial Procrustes superimposition and then use the results in statistical tests.  

Cheers!
Mike

**Comment by bernard-liew** [comment]
Many thanks for the kind response. The reason for exploring not doing a full GPA is from this article https://www.ncbi.nlm.nih.gov/pubmed/27175738. I will definitely keep in mind the change in statistical assumptions with and without doing a full GPA.

Bernard
