### ISSUE TITLE
minor readland.tps issue: "radii" within identifier

### ISSUE THREAD

**Issue by miltontan** [geomorphR/geomorph#14]
Hi all,

I'm having a minor readland.tps issue. One of my species names happens to contain the string "radii", so therefore readland.tps isn't reading the specimen names in this file. I can work around this, but I figured I should let you know.

Thanks!
Milton

**Comment by mlcollyer** [comment]
Hi Milton,

Thanks for the heads up.  I assume that you are using geomorph installed from CRAN or the Stable branch on our Github site?  If so, I wonder if I might ask a favor?  We updated this function on the Develop branch of our Github site and I think the problem you had might be averted.  I would be curious to know.  If you could try installing geomorph from our Develop branch (first have to install “devtools" if you have not done so, already), 

devtools::install_github(“geomorphR/geomoprh”, ref = “Develop”)

and then try to use readland.tps as before, without changing “radii”.  I wonder if you would get the same error.  We plan to update geomorph in the near future.  The Develop branch is like a beta version.  But we can also update one function on the Stable branch too if it proves to alleviate an error.  If you could confirm this for your data (or send a file to me, offline, if you want me to do it), that would help us out!

Cheers!
Mike

**Comment by miltontan** [comment]
Looks like the new readland.tps worked with no issues, so looks like you were one step ahead!

Thanks!

Milton Tan, Ph.D.
National Science Foundation Postdoctoral Fellow
George Washington University Visiting Scholar
Smithsonian Institution Research Associate
Fish Evolution and Genomics

On Apr 2, 2018, at 3:55 PM, Michael Collyer <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Milton,

Thanks for the heads up. I assume that you are using geomorph installed from CRAN or the Stable branch on our Github site? If so, I wonder if I might ask a favor? We updated this function on the Develop branch of our Github site and I think the problem you had might be averted. I would be curious to know. If you could try installing geomorph from our Develop branch (first have to install “devtools" if you have not done so, already),

devtools::install_github(“geomorphR/geomoprh”, ref = “Develop”)

and then try to use readland.tps as before, without changing “radii”. I wonder if you would get the same error. We plan to update geomorph in the near future. The Develop branch is like a beta version. But we can also update one function on the Stable branch too if it proves to alleviate an error. If you could confirm this for your data (or send a file to me, offline, if you want me to do it), that would help us out!

Cheers!
Mike

**Comment by mlcollyer** [comment]
Many thanks, Milton!  Glad it worked for you.  

Cheers!
Mike
