### ISSUE TITLE
JPEG decompression error

### ISSUE THREAD

**Issue by carlosmanacorda** [geomorphR/geomorph#19]
Hello everybody,

I am just trying to use geomorph to digitize my data for subsequent analysis. In a separate folder I have placed 13 photographs and created a .csv file with the names of each image (IMG_5859, IMG_5869 and so on) in a column. Then I wrote:

digitize2d("filelistColDL2.csv", nlandmarks=6, scale = NULL, tpsfile= "tpsoutputColDL2.tps", MultScale = FALSE, verbose = TRUE)

And the outcome:

Digitizing specimen 1 in filelist 
Error in readJPEG(filelist[i], native = T) : 
  JPEG decompression error: Not a JPEG file: starts with 0x49 0x4d

However, when I inspect the Properties of the images, they are said to be "Image JPEG (.JPG)".
![img_5859](https://user-images.githubusercontent.com/42445133/44219618-ecfa0a80-a152-11e8-9252-984345b580a5.JPG)
![img_5859](https://user-images.githubusercontent.com/42445133/44219663-03a06180-a153-11e8-9706-b6b7f89b0b9a.JPG)

So, were is the problem? And is there a way to fix it?

Many thanks in advance!

**Comment by deanadams** [comment]
Carlos,

You first need to read the  csv file into R, and then give that list to digitize2d.

Dean



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
