### ISSUE TITLE
compare.pls using 2B-PLS data output from MorphoJ

### ISSUE THREAD

**Issue by EveTC** [geomorphR/geomorph#25]
Hello fellow morphometric buddies!

I am very new to the world of geometric morphometrics, so my appologies if there is a simple soluation to my query. 

I have carried out two 2B-PLS analysis in MorphoJ with the first block as shape variables and second with enviornmental variables. I hope to compare these two 2B-PLS results as they are for the same species/samples and I would like to see if the shapes of the two structures are affected by the environmental variables the same way. 

I read the paper by Adams and Collyer (2016) in Evolution, which notes that the RV coefficient is not suitable to compare models due to it being sensitive to sample size etc. I therefore stumbled upon the function `compare.pls()`  in `geomorph`.

However, looking at the function is accepts data with a `class=pls`. Is there a way I can carry out the `compare.pls` function on data output from MorphoJ? The dataset I can output is a simple tab deliminated text file with the PLS scores for Block 1 and/or Block 2. Are PLS scores enough to carry out `compare.pls`? 

Thank you so much in advance for your advice.
Eve

**Comment by deanadams** [comment]
Eve,

The short answer is no. However, one can read in data, and use geomorph to perform GPA and then PLS.  PLS is found in several functions including: two.b.pls and integration.test (see help files). The output from these is in a format that compare.PLS can utilize. See that program's help file for details.

Dean
