### ISSUE TITLE
Bug rgl-0.100.30 (current CRAN rgl) impacts digit.fixed, fixed in devel svn

### ISSUE THREAD

**Issue by chris-english** [geomorphR/geomorph#27]
The bug referenced has to do with subscene indexes. In a new session, if you use geomorph to create landmarks, the first specimen goes smoothly. At the second specimen and thereafter, subscene is set (and not updated) in such a way that all attempts to place a new land mark on an area away from the last placed landmark in specimen 1 will offer acceptance at the last placed (subscene) on specimen 1, irrespective of where one has drawn one's selection box. 

see accepted answer: https://stackoverflow.com/questions/59678906/rgl-mouse-wheel-affects-only-last-subscene  

upgrade, via svn to higher version.
under linux:
svn checkout svn://svn.r-forge.r-project.org/svnroot/rgl/
cd to rgl/pkg
~/rgl/rgl/pkg$ R CMD build rgl # builds .tar.gz
(Oops)
Error: processing vignette 'rgl.Rmd' failed with diagnostics:
The orientlib package is needed for this function
 
as usual, need all dependencies, install whatever is missing and do again.
~/rgl/rgl/pkg$ R CMD build rgl # builds .tar.gz

~/rgl/rgl/pkg$ ls
rgl  rgl_0.100.46.tar.gz  rglwidget  tkrgl

~/rgl/rgl/pkg$ R CMD INSTALL rgl_0.100.46.tar.gz

**Comment by chris-english** [comment]
The bug referenced has to do with subscene indexes. In a new session, if you use geomorph to create landmarks, the first specimen goes smoothly. At the second specimen and thereafter, subscene is set (and not updated) in such a way that all attempts to place a new land mark on an area away from the last placed landmark in specimen 1 will offer acceptance at the last placed (subscene) on specimen 1, irrespective of where one has drawn one's selection box.

see accepted answer: https://stackoverflow.com/questions/59678906/rgl-mouse-wheel-affects-only-last-subscene

upgrade, via svn to higher version.
under linux:
svn checkout svn://svn.r-forge.r-project.org/svnroot/rgl/
cd to rgl/pkg
~/rgl/rgl/pkg$ R CMD build rgl # builds .tar.gz
(Oops)
Error: processing vignette 'rgl.Rmd' failed with diagnostics:
The orientlib package is needed for this function
As required install any missing dependencies and do again.

~/rgl/rgl/pkg$ R CMD build rgl # builds .tar.gz

~/rgl/rgl/pkg$ ls
rgl rgl_0.100.46.tar.gz rglwidget tkrgl

~/rgl/rgl/pkg$ R CMD INSTALL rgl_0.100.46.tar.gz

**Comment by antkal** [comment]
Thanks for the input. Unfortunately I can´t replicate the issue you mentioned. What version of R, rgl and geomorph are you running? Am I correct in assuming we are talking about using the function digitize2d? Or would that be a 3D case?
Cheers,
Antigoni
