### ISSUE TITLE
Landmarks & "Error in file(file, "r") : cannot open the connection"

### ISSUE THREAD

**Issue by 2902** [geomorphR/geomorph#30]
I recently installed Geomorph v 3.3.1 and the packages RRPP and rgl on RStudio V 1.3.959. This is for Mac.
I was doing the exercise on the link "geomorph digitizing Synopsis" on the cran page -->  https://cran.r-project.org/web/packages/geomorph/index.html

I started with:
library(geomorph)
library(RRPP) 
library(rgl) 
data("scallopPLY")
my.ply<-scallopPLY$ply

I have 2 issues:
- Can't run read.ply()
                  read.ply("my.ply",ShowSpecimen = T)
                                Error in file(file, "r") : cannot open the connection
- digit.fixed() function opens a window 3D plot through XQuartz, doesn't plot landmarks. Only once it plotted one landmark, but I wanted 5 landmarks.
                  fixed.lms1<-digit.fixed(spec=my.ply,fixed = 5)

Has anyone had this issue?

**Comment by deanadams** [comment]
This is not a bug; it is a usage issue.  The function ‘read.ply’ is used to read a *.ply file (please see the help file). You have tried to provide it a 3D mesh object already within R; that won’t work.

Dean

Dr. Dean C. Adams
Director of Graduate Education, EEB Program
Professor
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://www.eeob.iastate.edu/faculty/adams/
phone: 515-294-3834
