### ISSUE TITLE
Cannot plot bilat.symmetry object

### ISSUE THREAD

**Issue by VasLem** [geomorphR/geomorph#31]
Using R 4.0.3 on Ubuntu 20.04
rgl: 0.100.54
RRPP: 0.6.1

Test Case directly from the example:
```
data(scallops)
gdf <- geomorph.data.frame(shape = scallops$coorddata, ind = scallops$ind)
scallop.sym <- bilat.symmetry(A = shape, ind = ind, object.sym = TRUE,
curves= scallops$curvslide, surfaces = scallops$surfslide,
land.pairs=scallops$land.pairs, data = gdf, RRPP = TRUE, iter = 149)
summary(scallop.sym)
plot(scallop.sym, warpgrids = TRUE, mesh = NULL)
```

The error is:
```
Error in if (k == 2) { : argument is of length zero
```

**Comment by deanadams** [comment]
The error is not taken directly from the example. The error occurs in the line you added: 

plot(scallop.sym, warpgrids = TRUE, mesh = NULL)

That is not a valid line. The object 'scallop.sym' is not a specimen, but a summery from the bilat.symmetry function. It contains far more than just shapes. 

Please read the help file and vignettes for proper use of the function.

**Comment by VasLem** [comment]
Actually this line exists in the [PDF](https://cran.r-project.org/web/packages/geomorph/geomorph.pdf) documentation but is commented in this way:
```
# NOTE one can also: plot(scallop.sym, warpgrids = TRUE, mesh = NULL)
```
Sorry for not mentioning this fact. Can you please provide me with a working line for this example? I am fairly new in R

**Comment by mlcollyer** [comment]
The error was due to some legacy code in the plot function seeking an object that is not part of the output.  This has been fixed on the Github version of the package.  If you reinstall from Github, it should work now.  Please let us know if you have any other issues.

Mike

**Comment by VasLem** [comment]
Indeed after installing from Github, I got it working, thank you very much!
