### ISSUE TITLE
readmulti.nts Function Issues

### ISSUE THREAD

**Issue by rachsglee23** [geomorphR/geomorph#33]
Hello! I am a student relatively new to R hoping to use the "geomorph" package in order run a morphometric analysis of landmarked heads from microCT scans. We are trying to utilize the "readmulti.nts" function but have had some issues with the recent package version. I would greatly appreciate any guidance on how to solve this issue!

We were able to use geomorph version 3.3.1 to run the code attached below, however the updated 4.0.0 version of geomorph with the readmulti.nts function as a wrapper for the readland.nts function no longer allows for our code to work. Specifically, the readmulti.nts function is no longer compiling the nts files into a list with the correct dimensions (we are expecting to see 22 3 117, however, we continue to see 1 3 2552). 

<img width="302" alt="Screen Shot 2021-06-10 at 4 44 32 PM" src="https://user-images.githubusercontent.com/85316304/121594491-23dbf200-ca0b-11eb-854d-c11bfddfc020.png">
<img width="317" alt="Screen Shot 2021-06-10 at 4 49 54 PM" src="https://user-images.githubusercontent.com/85316304/121595062-e75cc600-ca0b-11eb-9139-e01c469a0ae3.png">

**Comment by deanadams** [comment]
This topic was covered a few weeks ago. If you install a new version of geomorph from GitHub, it should resolve the problem.

Best,


Deam

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: rachsglee23 ***@***.***>
Sent: Thursday, June 10, 2021 3:53:23 PM
To: geomorphR/geomorph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geomorphR/geomorph] readmulti.nts Function Issues (#33)


Hello! I am a student relatively new to R hoping to use the "geomorph" package in order run a morphometric analysis of landmarked heads from microCT scans. We are trying to utilize the "readmulti.nts" function but have had some issues with the recent package version. I would greatly appreciate any guidance on how to solve this issue!

We were able to use geomorph version 3.3.1 to run the code attached below, however the updated 4.0.0 version of geomorph with the readmulti.nts function as a wrapper for the readland.nts function no longer allows for our code to work. Specifically, the readmulti.nts function is no longer compiling the nts files into a list with the correct dimensions (we are expecting to see 22 3 117, however, we continue to see 1 3 2552).

[Screen Shot 2021-06-10 at 4 44 32 PM]<https://user-images.githubusercontent.com/85316304/121594491-23dbf200-ca0b-11eb-854d-c11bfddfc020.png>

[Screen Shot 2021-06-10 at 4 49 54 PM]<https://user-images.githubusercontent.com/85316304/121595062-e75cc600-ca0b-11eb-9139-e01c469a0ae3.png>

**Comment by rachsglee23** [comment]
Thank you for the prompt response. I followed the instructions to install the newest version of geomorph from GitHub as stated here: https://github.com/geomorphR/geomorph However, when doing so the error message below continues to pop up. Any guidance or suggestions would be greatly appreciated!

<img width="1372" alt="Screen Shot 2021-06-11 at 10 53 28 AM" src="https://user-images.githubusercontent.com/85316304/121706068-47527b80-caa3-11eb-9bc4-a6a4cd2b5012.png">

**Comment by deanadams** [comment]
Sorry
One also needs to install the latest RRPP from GitHub. My apologies for the omission.

Dean

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rachsglee23** [comment]
Unfortunately, in order to install the latest RRPP from GitHub I require the package Matrix to be installed first. I am having trouble installing this package to R -- it continues to ask for approval to use compilers, to which I've installed XCode as well as gfortran (which I confirmed installed correctly by running the hello.f90 test in terminal). However, install.packages("Matrix") results in non-zero status. When I try installing from source (downloading the tar.gz file and installing from Tools in R), it installs however it will not load using library(Matrix).

**Comment by mlcollyer** [comment]
The compilers are not part of RRPP or geomorph package requirements. I’m afraid you will have to sort that out with the package that is giving you trouble.  In the past I have had some success rebooting after updating Xcode. I have also had some success reinstalling R after having compilation issues. But this has been resolving by trial and error. 

Sorry to not have better advice. 

Mike

**Comment by rachsglee23** [comment]
Thank you for all of your help! Below I have attached my troubleshooting methods for this issue that solved my problem should anyone need it as a resource. 

What to do when “geomorph” will not load the proper packages

- Uninstall geomorph, RRPP, Matrix
- Ensure that XCode and gfortran is installed on computer
- When installing gfortran, download and open “.pkg” file, right click on file in Finder + Open
- Complete “Hello World” test in Terminal
- Install Matrix from source (download tar.gz file from r-forge.r-project.org and load from RStudio > Tools > Install Package)
- When prompted, say “no”
- As of 06/2021 - Matrix 1.3-3
- Install RRPP from source (similar to above)
- Install geomorph from GitHub
- **Note: will have to reinstall RStudio multiple times
