### ISSUE TITLE
Phylomorphospace troubles

### ISSUE THREAD

**Issue by StanleeKol** [geomorphR/geomorph#41]
Hi, while in old version 3.xx it works without issues, in 4.xx I am getting errors:
"Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': subscript out of bounds"

The trouble is my tree data. Please, I was wondering how the "plethspecies" was generated as it includes both landmarks and tree data but still work "data(plethspecies)" function. I understand that it is not geomorph data frame. Then what is it? I wanted to create something similar with my Y.gpa$coords and mytree.nex (tree data). Or any other suggestions what could help to resolve this issue?
Thank you.

Stan

**Comment by deanadams** [comment]
Stan,

Please install both RRPP and geomorph from Github and try again. There are updates to underlying code that affect gm.prcomp, and an issue was just identified and hopefully fixed.

Dean

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

From: stanleewild ***@***.***>
Sent: Wednesday, April 6, 2022 3:21 PM
To: geomorphR/geomorph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geomorphR/geomorph] Phylomorphospace troubles (Issue #41)


Hi, while in old version 3.xx it works without issues, in 4.xx I am getting errors:
"Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'as.matrix': subscript out of bounds"

The trouble is my tree data. Please, I was wondering how the "plethspecies" was generated as it includes both landmarks and tree data but still work "data(plethspecies)" function. I understand that it is not geomorph data frame. Then what is it? I wanted to create something similar with my Y.gpa$coords and mytree.nex (tree data). Or any other suggestions what could help to resolve this issue?
Thank you.

Stan

**Comment by StanleeKol** [comment]
Thank you Dean.

And please, should I use these commands?

install.packages("devtools")
devtools::install_github("geomorphR/geomorph", ref = "Stable", build_vignettes = TRUE)

AND

devtools::install_github("FinYang/RRRR")

**Comment by mlcollyer** [comment]
Stan,

geomorph does not depend on RRRR.  It does depend on RRPP.  Use:

devtools::install_github(“mlcollyer/RRPP”, build_vignettes = TRUE)

Cheers!
Mike

**Comment by StanleeKol** [comment]
My apologies, second was:
devtools::install_github("mlcollyer/RRPP")

I did that and it still has the same results.
Pipeline is:
classifier  <- read.csv("ClassifierAll.csv", header=T, row.names=1)
filelist <- list.files(pattern = ".nts")
mydata <- readmulti.nts(filelist)
readmulti.nts(filelist)
dim(mydata)
data(mydata)

Y.gpa<-gpagen(mydata)

plot(gm.prcomp(Y.gpa$coords))
PCA <- gm.prcomp(Y.gpa$coords)
tree <- read.tree("Tree_Ischnocera.nex")

#prune tips
species.to.keep <-read.csv("ClassifierAll.csv", header = TRUE)
pruned.tree<-drop.tip(tree,tree$tip.label[-na.omit(match(species.to.keep[,1],tree$tip.label))])
write.tree(pruned.tree, file = "pruned_tree.phy")
mytree <- read.tree("pruned_tree.phy")
name.check(mytree, classifier)

PCA.w.phylo <- gm.prcomp(Y.gpa$coords, phy = mytree).  ---->>**this part doesn't work**
summary(PCA.w.phylo)
summary(PCA.w.phylo)

**Comment by deanadams** [comment]
Stan,

Do the names in Y.gpa$coords match those in mytree? 

Dean

**Comment by StanleeKol** [comment]
name.check(mytree, classifier)
[1] "OK"
> name.check(mytree, Y.gpa$coords)
$tree_not_data
 [1] "Alcedoecus"        "Alcedoffula"       "Anaticola"         "Anatoecus"        
 [5] "Aquanirmus"        "Ardeicola"         "Austrogoniodes"    "Austrophilopterus"
 [9] "Brueelia"          "Campanulotes"      "Chelopistes"       "Colilipeurus"     
[13] "Columbicola"       "Craspedonirmus"    "Craspedorrhynchus" "Cuculoecus"       
[17] "Degeeriella"       "Docophoroides"     "Epicolinus"        "Esthiopterum"     
[21] "Fulicoffula"       "Goniodes"          "Halipeurus"        "Ibidoecus"        
[25] "Lipeurus"          "Megaginus"         "Meropoecus"        "Meropsiella"      
[29] "Neopsittaconirmus" "Osculotes"         "Oxylipeurus"       "Pectinopygus"     
[33] "Penenirmus"        "Pessoaiella"       "Philopterus"       "Pseudolipeurus"   
[37] "Psittoecus"        "Quadraceps"        "Rallicola"         "Saemundssonia"    
[41] "Splendoroffula"    "Strongylocotes"    "Sturnidoecus"      "Tinamotaecola"    
[45] "Vernoniella"      

$data_not_tree
 [1] "1"  "10" "11" "12" "13" "14" "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9" 

I checked it manually and it is the same. Only difference is that all Y.gpa$coords names have extension like "Alcedoecus.nts_1"
But the same data worked well in 3.xx R version with function "plotGMPhyloMorphoSpace"

**Comment by deanadams** [comment]
Wait, are you saying the names are actually not the same? That actually should not have worked before, as XXX != XXX_1.

What happens when you do: match(mytree$tip.labels, dimnames(Y.gpa$coords)[3] . If there is not a perfect match, you need to change the names in one or the other so that they correspond.

Dean

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

**Comment by StanleeKol** [comment]
> match(mytree$tip.labels, dimnames(Y.gpa$coords)[3])
integer(0)
> match(mytree$tip.labels, dimnames(Y.gpa$coords))
integer(0)

**Comment by deanadams** [comment]
Shoot! That’s tip.label (no s). Please try again.

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

**Comment by StanleeKol** [comment]
> match(mytree$tip.label, dimnames(Y.gpa$coords)[3])
 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[33] NA NA NA NA NA NA NA NA NA NA NA NA NA

**Comment by deanadams** [comment]
That might be the problem.  This should have numbers showing which species in the phylogeny is at which place in the data matrix.

Example from data ‘plethspecies’ you get:

match(plethspecies$phy$tip.label,dimnames(plethspecies$land)[[3]])

[1] 7 1 8 3 9 5 4 2 6

NOTE: need double brackets for the ‘3’ for dimnames.

Please confirm on this also. If you receive NA then it is a data error issue, and nothing in geomorph’s code.

Dean

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

**Comment by StanleeKol** [comment]
Yes, the same results. Please, what do you suggest me to do? How to remove in Y.gpa$coords that ".nts_1"?
Thank you very much.

Stan

**Comment by deanadams** [comment]
Yes. As with all R-based phylogenetic analysis packages, geomorph requires that the names in the data matrix and the phylogeny be identical.  Making them so in the data matrix should hopefully do the trick.

Best,

Dean

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

**Comment by StanleeKol** [comment]
I tried this:
> dimnames(Y.gpa$coords)[[3]] = gsub(pattern = ".nts_1", replacement = "", x = dimnames(Y.gpa$coords)[[3]])
> match(mytree$tip.label,dimnames(Y.gpa$coords)[[3]])
 [1] 34 30 39 36 44 26 42 10 22 15 16 35  1 33 40 38  2 45 12 27 28 43  9 37 29  8 17 25 31 11 41 19  3 20  5  4
[37] 21 24 32 23 18  6  7 14 13

It worked, thanks! Also one name was misspelled.

**Comment by deanadams** [comment]
Glad we’ve got you back on track. I’m closing the ticket now.

Best of luck with your project.

Dean

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834
