### ISSUE TITLE
Zoom while using digitize2d()

### ISSUE THREAD

**Issue by morgan-sparks** [geomorphR/geomorph#44]
Hello,  I am trying to digitize landmarks from some .jpg photos in Rstudio (on a Mac laptop)

When I import my jpg files with digitize2d(), the photos load into the Rstudio plot window very small. I read the quick guide and it discusses zooming in the digitize*3d*() function but it doesn't seem to work in my digitize2d function.  I think I might just be missing something obvious, but I can't figure out what it is.

Thanks!

**Comment by antkal** [comment]
Might be a better investment to look into the StereoMorph package for digitizing, then importing data into geomorph using the function readland.shapes. Although we are maintaining the digitizing functions active within geomorph, they are not being updated and might exhibit issues and irregularities in more recent computers.

**Comment by morgan-sparks** [comment]
Sounds good, thanks for the response and recommendation @antkal!
