### ISSUE TITLE
Error running example of Phylomorphospace

### ISSUE THREAD

**Issue by aConar** [geomorphR/geomorph#46]
Dear Dean,

Running the phylomorphospace example found in ?gm.prcomp throws an error:

```
data(plethspecies) 
Y.gpa <- gpagen(plethspecies$land)
PCA.w.phylo <- gm.prcomp(Y.gpa$coords, phy = plethspecies$phy)
summary(PCA.w.phylo)
plot(PCA.w.phylo, phylo = TRUE, main = "PCA.w.phylo")

Error: Some of the arguments in phylo.pars are different than those that are possible (see Arguments).
```
A new plot is showed but no tree nor nodes are shown, only the tip species.
Im running R version 4.3.3 (2024-02-29), with geomorph v4.0.7 and RRPP v2.0.0 in Debian 12.
Kind regards, 

Ale

**Comment by deanadams** [comment]
This has been addressed. It is in the plot parameters. Try reinstalling from github and running again.

D
Dr. Dean C. Adams
Distinguished Professor of Evolutionary Biology
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

From: aConar ***@***.***>
Sent: Wednesday, March 27, 2024 12:48 PM
To: geomorphR/geomorph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geomorphR/geomorph] Error running example of Phylomorphospace (Issue #46)


Dear Dean,

Running the phylomorphospace example found in ?gm.prcomp throws an error:

data(plethspecies)

Y.gpa <- gpagen(plethspecies$land)

PCA.w.phylo <- gm.prcomp(Y.gpa$coords, phy = plethspecies$phy)

summary(PCA.w.phylo)

plot(PCA.w.phylo, phylo = TRUE, main = "PCA.w.phylo")



Error: Some of the arguments in phylo.pars are different than those that are possible (see Arguments).

A new plot is showed but no tree nor nodes are shown, only the tip species.
Im running R version 4.3.3 (2024-02-29), with geomorph v4.0.7 and RRPP v2.0.0 in Debian 12.
Kind regards,

Ale

**Comment by aConar** [comment]
Thanks, it worked.
Ale
