### ISSUE TITLE
procD.lm: The number of observations in the input and output do not match.

### ISSUE THREAD

**Issue by aConar** [geomorphR/geomorph#49]
Hi,

I'm running a simple model with procD.lm, and it works well. My input data is in the form of a geomorph.data.frame, with a numeric matrix Y of 908x8 and a factor of the same length, 908. After running the model, e.g.,

`
fit1 <- procD.lm(Y ~ SP * SEX, data = GDATA, iter = 4999 )`

Cheking:
```
fit1$LM$n
[1] 705
```

Why there is a mismatch between the input data and the model data?
Thanks in advance,

Ale

**Comment by deanadams** [comment]
Ale,

Without seeing the upstream code and possibly the data, that is impossible to determine.

Here is a repeatable example demonstrating that they do line up properly when the upstream components are appropriate:

library(geomorph)
data(plethodon)
Y.gpa <- gpagen(plethodon$land)
gdf <-geomorph.data.frame(shape = Y.gpa$coords, spec = plethodon$species,
                          site = plethodon$site)
fit <- procD.lm(shape ~ spec * site, data = gdf)

fit$LM$n
dim(gdf$shape)

Dean

Dr. Dean C. Adams
Distinguished Professor of Evolutionary Biology
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

From: Ale ***@***.***>
Sent: Saturday, May 25, 2024 3:39 PM
To: geomorphR/geomorph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geomorphR/geomorph] procD.lm: The number of observations in the input and output do not match. (Issue #49)


Hi,

I'm running a simple model with procD.lm, and it works well. My input data is in the form of a geomorph.data.frame, with a numeric matrix Y of 908x8 and a factor of the same length, 908. After running the model, e.g.,

fit1 <- procD.lm(Y ~ SP * SEX, data = GDATA, iter = 4999 )

Cheking:

fit1$LM$n

[1] 705

Why there is a mismatch between the input data and the model data?
Thanks in advance,

Ale

**Comment by aConar** [comment]
Hi Dean,
The problem was on my data. Some NAs were introduced into the factor while curating the data, so interactions with NAs were excluded from the analysis. Thank you for the quick response!

Kind regards,
Ale

**Comment by deanadams** [comment]
Glad it was sorted out

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
