### ISSUE TITLE
Covariance explained by PLS axes

### ISSUE THREAD

**Issue by Caetanods** [geomorphR/geomorph#8]
This is a suggestion. The function 'phylo.integration' and 'two.b.pls' could return the percentage of the covariance explained by each of the PLS pair of axes. This would be an interesting feature to explore how many axes one need to explain most of the covariation in the data.

**Comment by mlcollyer** [comment]
Actually, the two.b.pls function provides that information, as one of the objects output in the list is the SVD of the cross-covariance matrix.  But it's a good suggestion to do the same in integration.test and phylo.integration.  Thank you!

**Comment by nicolegrunstra** [comment]
I'm glad this comment has been made, because I missed the value expressing percentage covariance explained by phylo.integration. Especially because this allows a great comparison of explanatory power  of phylogenetic and non-phylogenetic 2B-PLS.

**Comment by nicolegrunstra** [comment]
Further to my comment above, there is no output object that actually lists the % covariance explained by the PLS axes, but neither does the two.b.pls. But following Mike's comment above, the output r.pls (automatically produced for LV1) represents the proportion of covariance concentrated in LV1. One can correlate the X and Y scores of subsequent vectors/axes and obtain the information we want about relative covariance explained. And this procedure is identical for phylo.integration.
